name: Astro Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
          
      - name: Install
        shell: "bash"
        run: npm install
        
      - name: Build
        shell: "bash"
        run: npm run build
        
      - name: Deploy
        uses: appleboy/scp-action@master
        with: 
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: dist
          target: /home/websites/ban
      
